name: TEST MEXC COIN LIST

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Repo indir
        uses: actions/checkout@v3

      - name: Python kur
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Gerekli paketleri kur
        run: |
          pip install requests ccxt pandas numpy

      - name: Test scripti çalıştır
        run: |
          python test_mexc_list.py
