name: test_run
on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Repo checkout
        uses: actions/checkout@v3

      - name: Python kurulum
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Pip install
        run: pip install pandas requests

      - name: Test Binance visibility
        run: python test_binance_visibility.py
